apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.yml: |
    # This properties file should be used to initialise a ConfigMap
    greeting:
      message: "Hello %s from a ConfigMap!"
