apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-view-default
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-view-jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
