# Workaround for issue with Dekorate: https://github.com/dekorateio/dekorate/pull/851
management.endpoints.web.exposure.include: health,info
# Dekorate
dekorate:
  openshift:
    expose: true
  s2i:
    builder-image: registry.access.redhat.com/ubi8/openjdk-11:1.14
