apiVersion: v1
kind: List
items:
  # ConfigMap to be created to pass application.yml content to Spring Boot
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: app-config
    data:
      application.yml: |
        # This properties file should be used to initialise a ConfigMap
        greeting:
          message: "Hello %s from a ConfigMap!"
  - kind: Role
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: app-config-role
    rules:
      - apiGroups: [ "" ]
        resources: [ "configmaps", "pods", "services", "endpoints", "secrets" ]
        verbs: [ "get", "list", "watch" ]
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: app-config-role-binding
    subjects:
      - kind: ServiceAccount
        name: default
        apiGroup: ""
    roleRef:
      kind: Role
      name: app-config-role
      apiGroup: ""
